### ISSUE TITLE
Upscale Factor

### ISSUE THREAD

**Issue by nonick2k23** [Algolzw/BSRT#11]
I want to thank you for the assistance at the other thread.

I am wondering if it is possible to modify the network to provide upscale of x2 instead of x8?

I noticed that the network contains three pixel shuffles, each up-scaled by x2, so we have x2 on x2 on x2 -> x8 up-scaled image in the end.

Did you experiment with x2 upscale? Do you have suggestions how to modify the network so x2 upscale works with optimal results? 

Thanks

**Comment by Algolzw** [comment]
Hi, we haven't tried x2 scale upsampling yet. Now our code works on the RAW images so it uses the first x2 to parse 'RGGB' RAW format to a normal image and then uses two x2 to perform x4 SR.

If you want to perform x2 on RAW images you can remove the third x2 operation. And if you want to perform x2 SR on RGB images, you need to remove the first x2 operation as well.

Best.

**Comment by nonick2k23** [comment]
Thanks
