### ISSUE TITLE
about the spatial scale in L3layer and SPynet

### ISSUE THREAD

**Issue by K1NSA** [Algolzw/BSRT#13]
Dear author,
Thanks for your work. My work also use a kind of PCD, in the l3 layer ,the H,W =[32,32]. And the SPyNet down sample 32 times , so the input is H,W=[1,1]. Is this possible to use spy net to calculate optical flow?

**Comment by Algolzw** [comment]
Hi! As my experience, if your input size is different with the required size of SpyNet, you can resize the input to match the SpyNet!

**Comment by K1NSA** [comment]
> 
Thanks for your answer, by the way, what's the input size of your training data? Is it H,W=[256,256]?

**Comment by Algolzw** [comment]
For synthetic data, yes its input size is [256 x 256], but for real-world data, its input size is [160 x 160]. But any size should be fine once it can be processed by SpyNet ($> 2^5$).
