### ISSUE TITLE
关于测试script的canon数据集

### ISSUE THREAD

**Issue by anguoyang** [Algolzw/BSRT#7]
@Algolzw 您好，我试着用test_real.py，而且也从https://github.com/goutamgmb/NTIRE21_BURSTSR下载了三星的raw 测试数据，但是貌似还需要canon/GT数据集，要不然会报错，
`ntire21/burstsr/real/val/0021_0000/canon/im_raw.png'): can't open/read file: check file path/integrity`
请问这个canon的数据集在哪里下载？谢谢

**Comment by Algolzw** [comment]
Hello, real-world的数据集可以用这个[DBSR](https://github.com/goutamgmb/deep-burst-sr)提供的[script](https://github.com/goutamgmb/deep-burst-sr/blob/master/util_scripts/download_burstsr_dataset.py)下载。如果只想下载验证集的话[点这个](https://data.vision.ee.ethz.ch/bhatg/BurstSRChallenge/val.zip)。

**Comment by anguoyang** [comment]
非常感谢！
